feat: v2 addon format
ember-a11y/ember-a11y-refocus pull request #390
Opened 2024-12-24 12:30 UTC by aklkv

2025-01-07 23:05 UTC, aklkv commented
@MelSumner I think this is ready to go, and hopefully  CI passes, I have tested everything locally

2025-01-10 14:33 UTC, josephdsumner commented on package.json
> -  "author": "Melanie Sumner <melaniersumner@gmail.com>",
Please preserve this information in the project's new `package.json` files.

2025-01-10 14:40 UTC, josephdsumner commented on addon/package.json
> +  "name": "ember-a11y-refocus",
@MelSumner 

The community convention here seems to be that this folder (`addon`) is given name of the addon package. This would be:

```sh
ember-a11y-refocus/
    ember-a11y-refocus/
        src/
    test-app/
```

What do you think?

2025-01-10 14:59 UTC, josephdsumner commented on addon/src/components/navigation-narrator.gts
> +      // eslint-disable-next-line ember/no-runloop
@aklkv 

What are your thoughts on using `ember-lifeline` vs. `ember-concurrency` here?

2025-01-10 15:02 UTC, josephdsumner commented on addon/src/components/navigation-narrator.gts
> +      Object.keys(this.transition?.to?.queryParams || {}).length > 0
We can double check the docs for this, but don't think you need to allow for undefined on `to`, provided you have the `transition`. I think it would type-check all the way down.

If the transition originates from an initial load of the application (like directly loading a route via a URL), the `from` attribute is null because there is no previous route (so keep the `?`). If memory serves me correctly, the `to` should always exist because there should always be a target.

2025-01-10 20:16 UTC, MelSumner commented
> @MelSumner I think this is ready to go, and hopefully  CI passes, I have tested everything locally 

I'll do my best to review this ASAP, can you make sure to update the PR description with the changes made?

2025-01-10 20:19 UTC, MelSumner commented on addon/src/components/navigation-narrator.gts
> +      Object.keys(this.transition?.to?.queryParams || {}).length > 0
@josephdsumner I think we ended up needing to add it before but I can't remember exactly why.

2025-01-10 21:25 UTC, aklkv commented on package.json
> -  "author": "Melanie Sumner <melaniersumner@gmail.com>",
It is preserved in the addon workspace which is the main published part of the repo

2025-01-10 21:27 UTC, aklkv commented on addon/package.json
> +  "name": "ember-a11y-refocus",
I have seen both patterns used, and since it's singular addon workspace it probably make sense to name it `addon` and I found it a little strange to move around locally, but this might be just me

2025-01-10 21:28 UTC, aklkv commented on addon/src/components/navigation-narrator.gts
> +      // eslint-disable-next-line ember/no-runloop
this could be a follow up item and outside of the scope of this PR which is already big enough

2025-01-10 22:02 UTC, MelSumner commented on addon/package.json
> +  "name": "ember-a11y-refocus",
@josephdsumner thanks for bringing this up. I agree with @aklkv here, and also as the primary maintainer for this particular addon, I just don't prefer that naming structure.

2025-01-10 22:02 UTC, MelSumner commented on addon/package.json
> +  "author": "Melanie Sumner <melaniersumner@gmail.com>",
@aklkv would it make sense to add the `contributors` attribute to the addon now that more folks are pitching in? WDYT?

2025-01-10 22:07 UTC, MelSumner commented on addon/src/components/navigation-narrator.gts
> +      // eslint-disable-next-line ember/no-runloop
I've filed a follow up issue: https://github.com/ember-a11y/ember-a11y-refocus/issues/392

2025-01-10 22:09 UTC, aklkv commented on addon/package.json
> +  "author": "Melanie Sumner <melaniersumner@gmail.com>",
sure thing, I can do that, is there anyone in particular you want me to add to this field?

2025-01-10 22:11 UTC, MelSumner commented on test-app/README.md
> +A short introduction of this app could easily go here.
This is the test app for the `ember-a11y-refocus` addon.

2025-01-10 22:14 UTC, josephdsumner commented on package.json
> -  "author": "Melanie Sumner <melaniersumner@gmail.com>",
Sounds great, thanks!

2025-01-10 22:15 UTC, josephdsumner commented on addon/src/components/navigation-narrator.gts
> +      // eslint-disable-next-line ember/no-runloop
Sounds good -- non-blocking question 👍

2025-01-10 22:32 UTC, josephdsumner commented on addon/src/components/navigation-narrator.gts
> +      Object.keys(this.transition?.to?.queryParams || {}).length > 0
@MelSumner 

I don't remember exactly why either -- should we consider this (and similar) to get scoped under migrating the addon to TS in full?

2025-01-13 16:40 UTC, josephdsumner commented on addon/package.json
> +  "author": "Melanie Sumner <melaniersumner@gmail.com>",
We can add the organization members for `ember-a11y` + contributors on the repo itself?

https://github.com/orgs/ember-a11y/people

Something like:

https://github.com/ember-a11y/ember-a11y-testing/blob/15bfba20b9a3d723cab56ff7489e6f1e7ff0ed21/package.json#L15

2025-01-13 16:41 UTC, MelSumner commented
This is looking pretty good. I think just two more things before moving forward: 

1. @aklkv if you can please update the description to reflect the changes made, since this goes into the release notes
2. I'd like to get another set of eyes on this, maybe a v2 addon guru (@ef4 or @mansona ??) or another regular contributor to the repo (maybe @jgwhite if he has a spare cycle)

2025-01-13 18:20 UTC, josephdsumner commented
> This should close a number if open issues. Once this is merged we can look into adding relase-plan.
> 
> Breaking changes:
> 
> * if consumer need css, it has to be now imported manually

@aklkv 

**Question**: Do we need to do something similar in order for the `stylelint` floating-deps check to work properly?

2025-01-17 16:36 UTC, MelSumner commented on addon/src/components/navigation-narrator.gts
> +      Object.keys(this.transition?.to?.queryParams || {}).length > 0
That sounds good to me 👍

2025-01-17 16:37 UTC, MelSumner commented on addon/package.json
> +  "author": "Melanie Sumner <melaniersumner@gmail.com>",
Just the contributors to this repo, thanks @aklkv !

2025-01-17 18:25 UTC, MelSumner commented on addon/package.json
> +  "author": "Melanie Sumner <melaniersumner@gmail.com>",
Actually, I've moved this to a separate issue: https://github.com/ember-a11y/ember-a11y-refocus/issues/393

2025-01-17 18:30 UTC, MelSumner requested changes
Three things: 

1. Please review the test that is failing 
2. Check the updated description, I gave it a go but there may be more we wish to include. 
3. Please add instructions to the README for how users need to import the CSS for the addon; I think that would be appropriate for this PR, since that changed in this PR. 

Anything else that was a nice-to-have has been moved to separate issues. 

Thank you so much! Can't wait to get this out as a new release!

2025-01-17 18:39 UTC, josephdsumner approved these changes
Approving this PR with the expectation that the sole outstanding `floating-dependencies` issue will be resolved before merge + release. It looks great and both mine and @MelSumner 's change requests have either been made or appropriately scoped elsewhere.

👍

2025-01-19 19:07 UTC, josephdsumner commented on addon/.stylelintignore
👍 thanks for looking into this -- I have approved the CI run.

2025-01-19 19:13 UTC, josephdsumner commented on addon/.stylelintignore
No luck -- I'll take a closer look at this against the latest v2 addon blueprint for stylelint deps / versions / config.

2025-01-19 21:54 UTC, aklkv commented on addon/.stylelintignore
I have a idea that it might be relate to pnpm v10 and `--no-lockfile` option, it might have been removed

2025-01-19 21:57 UTC, aklkv commented on addon/.stylelintignore
yep, here we go https://github.com/pnpm/pnpm/issues/8865

2025-01-20 12:38 UTC, josephdsumner commented on addon/.stylelintignore
Happy to see the fix has been identified and merged upstream. I'd hope for a quick turnaround for a release with our blocker fixed in there. Pnpm shipping a larger, slower release with a wave of fixes for the new major would be understandable. 

**Question:** what do you think about filing this issue as a blocker for cutting our next release, but not letting it block this PR?

2025-01-20 22:36 UTC, aklkv commented on addon/.stylelintignore
Yeah it's not blocking at all, just nice to have. I have commented out this flag for now, since CI is green I think we are gtg, I will add some readme update in a bit + create follow up PR for uncommenting pnpm flag

2025-01-21 12:57 UTC, josephdsumner commented on addon/.stylelintignore
**Question:** is there any reason we can't keep pnpm@9 and ship both the PR and release immediately?

2025-01-21 18:36 UTC, aklkv commented on addon/.stylelintignore
you can ship immediately on pnpm@v10, without follow up PR as it's not really important for end consumer

2025-01-22 14:05 UTC, MelSumner approved these changes
Ok, I think this is good for now, we'll follow up with a few more PRs before cutting a release. Thank you for your contributions!!

2025-01-22 14:09 UTC, merged